### ISSUE TITLE
TraceRoute.Result append  NullPointerException

### ISSUE THREAD

**Issue by yongyu0102** [qiniu/android-netdiag#3]
TraceRoute 检测 unknown host 会报出空指针异常，解决方式是 ：
 private void updateOut(String str) {
//添加 null 判断
        if(result !=null){
            result.append(str);
        }
    }

 private void printNormal(Matcher m, long time, StringBuilder lineBuffer) {
        if(result !=null){
            result.append(lineBuffer.toString());
        }
    }

**Comment by longbai** [comment]
fixed in 0.11

**Comment by love999** [comment]
not fixed in 0.11

still got

java.lang.NullPointerException: Attempt to invoke direct method 'void com.qiniu.android.netdiag.TraceRoute$Result.append(java.lang.String)' on a null object reference
                                                                               at com.qiniu.android.netdiag.TraceRoute$Result.access$100(TraceRoute.java:210)
                                                                               at com.qiniu.android.netdiag.TraceRoute.updateOut(TraceRoute.java:151)
                                                                               at com.qiniu.android.netdiag.TraceRoute.run(TraceRoute.java:161)
                                                                               at com.qiniu.android.netdiag.TraceRoute.access$000(TraceRoute.java:16)
                                                                               at com.qiniu.android.netdiag.TraceRoute$1.run(TraceRoute.java:63)
                                                                               at java.lang.Thread.run(Thread.java:764)
06
